import{a as p,i as f,S as E,l as T}from"./assets/vendor-02569a35.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const S="20604497-76eef09585394ebdddc8f0af4",u=40,n={form:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),guard:document.querySelector(".guard"),goTop:document.querySelector(".js-go-top")};function A(){const{height:e}=n.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function q(){window.scrollTo({top:0,behavior:"smooth"})}p.defaults.baseURL="https://pixabay.com/api/";p.defaults.params={key:S,image_type:"photo",per_page:u,orientation:"horizontal",safesearch:!0};class P{constructor(){this.query="",this.page=1}async getPhoto(){const o=await p({params:{q:this.query,page:this.page}});if(o.status!==200)throw new Error(o.statusText);return o.data}nextPage(){this.page+=1}set searchQuery(o){this.query=o}get searchQuery(){return this.query}startPage(){this.page=1}}const l=new P;function _(e){return e.trim().toLowerCase().replace(/\s/g,"+")}function y(e){return e.map(({webformatURL:o,tags:a,likes:s,views:t,largeImageURL:r,comments:c,downloads:L})=>`<div class="photo-card" data-text=${a} data-large=${r}>
    <div class="photo-wrapper" >
    <img class="photo" src="${o}" alt="${a}" loading="lazy"  />
    </div>
    <div class="info">
        <p class="info-item">
            <b>Likes</b>${s}
        </p>
            <p class="info-item">
        <b>Views</b>${t}
        </p>
        <p class="info-item">
            <b>Comments</b>${c}
        </p>
        <p class="info-item">
            <b>Downloads</b>${L}
        </p>
    </div>
</div>`).join("")}const x=3e3,H="Sorry, there are no images matching your search query. Please try again",M="We're sorry, but you've reached the end of search results.",i={timeout:x,position:"topRight"};function k(e){i.title="Hooray!",i.message=`We found ${e} images.`,f.success(i)}function b(e){i.title="Error",i.message=e||H,f.error(i)}function w(){i.title="Warning",i.message=M,f.warning(i)}const d={selector:".photo-card",srcImage:"data-large",caption:"data-text"},v=new E(d.selector,{sourceAttr:d.srcImage,captionsData:d.caption,captionDelay:250,animationSpeed:500}),g=n.form.elements.searchQuery;n.form.addEventListener("submit",$);g.addEventListener("input",T(R,300));n.goTop.addEventListener("click",O);window.addEventListener("scroll",h);window.addEventListener("load",h);function R(){const e=n.form.elements[1];if(!g.value||!g.value.trim().length){e.disabled=!0;return}e.disabled&&(e.disabled=!1)}async function $(e){e.preventDefault();const o=_(e.currentTarget.children.searchQuery.value);o!==l.searchQuery&&(m.unobserve(n.guard),l.startPage(),l.searchQuery=o,n.gallery.innerHTML="");try{const a=await l.getPhoto(),{totalHits:s,hits:t}=a;if(!s)throw new Error("");s<=u?w():s>u&&(m.observe(n.guard),k(s));const r=y(t);n.gallery.insertAdjacentHTML("beforeend",r),v.refresh()}catch(a){console.log(a),b(a.message)}}const I={rootMargin:"400px"},D=(e,o)=>{e.forEach(async a=>{if(a.isIntersecting){l.nextPage();try{const s=await l.getPhoto(),{totalHits:t,hits:r}=s;t<u*l.page&&(o.unobserve(n.guard),w());const c=y(r);n.gallery.insertAdjacentHTML("beforeend",c),v.refresh(),A()}catch(s){console.log(s),b(s.message)}}})},m=new IntersectionObserver(D,I);function O(){q()}function h(){window.removeEventListener("load",h),window.scrollY>800?n.goTop.classList.remove("visually-hidden"):n.goTop.classList.add("visually-hidden")}
//# sourceMappingURL=commonHelpers.js.map
